"""esquema inicial weather intelligence

Revision ID: d3ba39744a07
Revises: 
Create Date: 2026-09-09 00:15:16.442316+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd3ba39744a07'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k', sa.SmallInteger(), nullable=False),
    sa.Column('silhouette', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('centroids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_models'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('elevation_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('slug', name=op.f('uq_locations_slug'))
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('horizon_hours', sa.SmallInteger(), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('train_period', sa.String(length=60), nullable=True),
    sa.Column('valid_period', sa.String(length=60), nullable=True),
    sa.Column('test_period', sa.String(length=60), nullable=True),
    sa.Column('mae', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('r2', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_index('ix_model_runs_is_active', 'model_runs', ['is_active'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('ai_analyses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_ai_analyses_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index('ix_ai_analyses_location_id_generated_at', 'ai_analyses', ['location_id', 'generated_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('base_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_predictions_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name=op.f('fk_predictions_model_run_id_model_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('ix_predictions_location_id_target_time', 'predictions', ['location_id', 'target_time'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('temperature_2m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('relative_humidity_2m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dew_point_2m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('apparent_temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('surface_pressure', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_msl', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rain', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('snowfall', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cloud_cover_low', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cloud_cover_mid', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cloud_cover_high', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_10m', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_gusts_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_100m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('shortwave_radiation', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('direct_radiation', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('diffuse_radiation', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('et0_fao_evapotranspiration', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('weather_code', sa.SmallInteger(), nullable=True),
    sa.Column('is_day', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('historical', 'realtime')", name=op.f('ck_weather_observations_source_allowed')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_weather_observations_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations')),
    sa.UniqueConstraint('location_id', 'observed_at', 'source', name=op.f('uq_weather_observations_location_id_observed_at_source'))
    )
    op.create_index('ix_weather_observations_location_id_observed_at', 'weather_observations', ['location_id', 'observed_at'], unique=False)
    op.create_index('ix_weather_observations_source', 'weather_observations', ['source'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('detector', sa.String(length=40), nullable=False),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_anomalies_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_id'], ['weather_observations.id'], name=op.f('fk_anomalies_observation_id_weather_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies')),
    sa.UniqueConstraint('observation_id', 'detector', name=op.f('uq_anomalies_observation_id_detector'))
    )
    op.create_index('ix_anomalies_location_id_observed_at', 'anomalies', ['location_id', 'observed_at'], unique=False)
    op.create_table('cluster_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_model_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.SmallInteger(), nullable=False),
    sa.Column('distance_to_centroid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['cluster_model_id'], ['cluster_models.id'], name=op.f('fk_cluster_assignments_cluster_model_id_cluster_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['weather_observations.id'], name=op.f('fk_cluster_assignments_observation_id_weather_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_assignments')),
    sa.UniqueConstraint('cluster_model_id', 'observation_id', name=op.f('uq_cluster_assignments_cluster_model_id_observation_id'))
    )
    op.create_index('ix_cluster_assignments_cluster_model_id_cluster_id', 'cluster_assignments', ['cluster_model_id', 'cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_assignments_cluster_model_id_cluster_id', table_name='cluster_assignments')
    op.drop_table('cluster_assignments')
    op.drop_index('ix_anomalies_location_id_observed_at', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_weather_observations_source', table_name='weather_observations')
    op.drop_index('ix_weather_observations_location_id_observed_at', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('ix_predictions_location_id_target_time', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_ai_analyses_location_id_generated_at', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_model_runs_is_active', table_name='model_runs', postgresql_where=sa.text('is_active'))
    op.drop_table('model_runs')
    op.drop_table('locations')
    op.drop_table('cluster_models')
    # ### end Alembic commands ###
