"""retraining_runs table

Revision ID: d8dc2bbbe11d
Revises: 517f8b742b79
Create Date: 2026-09-14 16:26:06.942609+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd8dc2bbbe11d'
down_revision: str | None = '517f8b742b79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retraining_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trigger_reason', sa.String(length=40), nullable=False),
    sa.Column('n_new_observations', sa.Integer(), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_retraining_runs_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retraining_runs'))
    )
    op.create_index('ix_retraining_runs_location_id_triggered_at', 'retraining_runs', ['location_id', 'triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retraining_runs_location_id_triggered_at', table_name='retraining_runs')
    op.drop_table('retraining_runs')
    # ### end Alembic commands ###
